#!/usr/bin/env node
// frame-to-aot.js — transpile a sumi command frame (frame.json: a JSON array of
// { name, nums, text? } commands) into a NeLisp AOT program (.el) that renders
// it natively in a GTK4 window via cairo, with NO Rust and NO emacs-ffi-call —
// the drawing is the AOT extern-call FFI path (dev/nelisp examples/ffi-cairo).
//
// Each sumi dtw-* command maps to cairo calls; coordinates / colours are known
// at transpile time, so they are emitted as f64 immediates `(:f64 N.N)`.
//
//   node frame-to-aot.js [frame.json] [out.el]
//
// Then compile + run with the dev/nelisp harness:
//   bash ../../../nelisp/examples/ffi-cairo/gtkwin.sh out.el /tmp/sumi-frame \
//        $(pkg-config --libs gtk4)
'use strict';
const fs = require('fs');
const inPath = process.argv[2] || 'frame.json';
const outPath = process.argv[3] || 'sumi-frame-render.el';
const frame = JSON.parse(fs.readFileSync(inPath, 'utf8'));

// ---- string interning → data-blobs --------------------------------------
const strings = new Map();            // raw string -> blob symbol
function blob(s) {
  s = String(s);
  if (strings.has(s)) return strings.get(s);
  const sym = 's_' + strings.size;
  strings.set(s, sym);
  return sym;
}
// escape a JS string for an elisp string literal (the AOT reader reads UTF-8).
function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
// format an integer/number as an f64 literal cairo wants.
function f(n) { return Number.isInteger(n) ? n.toFixed(1) : String(Number(n)); }
function col(v) { return (Math.max(0, Math.min(255, v)) / 255).toFixed(4); }

// ---- walk the command stream → cairo body -------------------------------
let W = 240, H = 120;
let px = 0, py = 0;                    // current text position (dtw-set-position)
const body = [];
const E = (s) => body.push('      ' + s);
for (const c of frame) {
  const n = c.nums || [];
  switch (c.name) {
    case 'gui-screen': case 'dtw-screen':
      W = n[1] | 0; H = n[2] | 0; break;
    case 'gui-buffer-select': case 'dtw-select-buffer':
      break;                          // single buffer: no-op
    case 'gui-set-color': case 'dtw-set-color':
      E(`(extern-call cairo_set_source_rgb cr (:f64 ${col(n[0])}) (:f64 ${col(n[1])}) (:f64 ${col(n[2])}))`);
      break;
    case 'gui-set-font': case 'dtw-set-font':
      E(`(extern-call cairo_select_font_face cr (data-addr ${blob(c.text || 'sans')}) 0 0)`);
      E(`(extern-call cairo_set_font_size cr (:f64 ${f(n[0] || 12)}))`);
      break;
    case 'gui-set-position': case 'dtw-set-position':
      px = n[0] | 0; py = n[1] | 0; break;
    case 'gui-fill-rect': case 'dtw-fill-rect':
      E(`(extern-call cairo_rectangle cr (:f64 ${f(n[0])}) (:f64 ${f(n[1])}) (:f64 ${f(n[2])}) (:f64 ${f(n[3])}))`);
      E(`(extern-call cairo_fill cr)`);
      break;
    case 'gui-draw-line': case 'dtw-draw-line':
      E(`(extern-call cairo_set_line_width cr (:f64 1.0))`);
      E(`(extern-call cairo_move_to cr (:f64 ${f(n[0])}) (:f64 ${f(n[1])}))`);
      E(`(extern-call cairo_line_to cr (:f64 ${f(n[2])}) (:f64 ${f(n[3])}))`);
      E(`(extern-call cairo_stroke cr)`);
      break;
    case 'gui-draw-point': case 'dtw-draw-point':
      E(`(extern-call cairo_rectangle cr (:f64 ${f(n[0])}) (:f64 ${f(n[1])}) (:f64 1.0) (:f64 1.0))`);
      E(`(extern-call cairo_fill cr)`);
      break;
    case 'gui-draw-text': case 'dtw-draw-text':
      E(`(extern-call cairo_move_to cr (:f64 ${f(px)}) (:f64 ${f(py)}))`);
      E(`(extern-call cairo_show_text cr (data-addr ${blob(c.text || '')}))`);
      break;
    default:
      // image / unhandled commands are skipped in this first cut
      E(`;; (skipped ${c.name})`);
      break;
  }
}

// ---- emit the .el --------------------------------------------------------
const blobs = [];
blobs.push(` (data-blob title       "sumi frame (NeLisp AOT, native GTK4)\\0" rodata)`);
blobs.push(` (data-blob sig_destroy "destroy\\0" rodata)`);
for (const [s, sym] of strings) {
  blobs.push(` (data-blob ${sym} "${esc(s)}\\0" rodata)`);
}

const el = `;; GENERATED by frame-to-aot.js from ${inPath} — do not edit by hand.
;; Renders one sumi command frame natively via the NeLisp AOT cairo/GTK4 FFI
;; (no Rust, no emacs-ffi-call).  ${frame.length} commands, ${W}x${H}.
(seq
${blobs.join('\n')}

 (defun on_draw (area cr width height ctx)
   (seq
${body.join('\n')}
      0))

 (defun on_quit (ctx)
   (seq (extern-call g_main_loop_quit (ptr-read-u64 ctx 0)) 0))
 (defun on_destroy (widget ctx)
   (seq (extern-call g_main_loop_quit (ptr-read-u64 ctx 0)) 0))

 (defun main ()
   (seq
    (extern-call gtk_init)
    (let ((ctx (extern-call malloc 8)))
      (let ((window (extern-call gtk_window_new)))
        (seq
         (extern-call gtk_window_set_title window (data-addr title))
         (extern-call gtk_window_set_default_size window ${W} ${H})
         (let ((area (extern-call gtk_drawing_area_new))
               (loop (extern-call g_main_loop_new 0 0)))
           (seq
            (ptr-write-u64 ctx 0 loop)
            (extern-call gtk_widget_set_size_request area ${W} ${H})
            (extern-call gtk_drawing_area_set_draw_func area (addr-of on_draw) ctx 0)
            (extern-call gtk_window_set_child window area)
            (extern-call g_signal_connect_data
                         window (data-addr sig_destroy) (addr-of on_destroy) ctx 0 0)
            (extern-call g_timeout_add 30000 (addr-of on_quit) ctx)
            (extern-call gtk_window_present window)
            (extern-call g_main_loop_run loop)
            0))))))))
`;
fs.writeFileSync(outPath, el);
console.error(`OK: ${frame.length} cmds, ${strings.size} strings, ${W}x${H} -> ${outPath}`);
